# Generated by Django 5.1.7 on 2025-08-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='user_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
